import Head from "next/head";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Content from "@/components/content"

export default function Main() {
  return (
    <div>
      <Head>
        <title>Create Next App 4 Sosmed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content />
      <Footer />
    </div>
  );
}

